Homepage/Models/ErrorViewModel.cs
using System;

namespace Homepage.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Homepage/Models/RssItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Rewrite.Internal;

namespace Homepage.Models
{
	public class RssItem
	{
		public string Title { get; set; }

		public string Author { get; set; }

		public DateTime DatePublished { get; set; }

		public string Description { get; set; }

		public string Url { get; set; }
    }
}

Homepage/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Homepage.Models;
using Homepage.NewsAggregator;
using Microsoft.WindowsAzure.Storage.Blob.Protocol;

namespace Homepage.Controllers
{
    public class HomeController : Controller
    {
	    public int PageSize = 7;

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

	    public IActionResult NewsAggregator(int? page)
	    {
			RSSReader reader = new RSSReader();
		    var newsFeed = reader.GetNewsFeed();
		    if (!page.HasValue)
		    {
			    page = 1;
		    } 
		    ViewBag.page = page;
		    ViewBag.lastPage = Math.Ceiling((decimal)(newsFeed.Count / 5));
		    if (page > 1)
		    {
			    return View(newsFeed.Skip(((page - 1) * 5).GetValueOrDefault()).Take(PageSize));
			}
		    else
		    {
			    return View(newsFeed.Take(PageSize));
			}
			
	    }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Homepage/Controllers/MapGeneratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Homepage.Controllers
{
    public class MapGeneratorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Homepage/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Homepage/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Homepage/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}

<!-- Header -->
<header id="header">
	<a asp-controller="Home" asp-action="Index" class="logo"><strong>Sandbox</strong> - A Study in Trial and Error</a>
	<ul class="icons">
		<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
		<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
	</ul>
</header>

<!-- Banner -->
<section id="banner">
	<div class="content">
		<header>
			<h1>
				Sarah Caldow
			</h1>
			<p>Programming and Other Assorted Artforms</p>
		</header>
		<p>Aenean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.</p>
		<ul class="actions">
			<li><a href="#" class="button big">Learn More</a></li>
		</ul>
	</div>
	<span class="image object">
		<img src="images/pic10.jpg" alt="" />
	</span>
</section>

Homepage/Views/Home/NewsAggregator.cshtml
@model IEnumerable<RssItem>
@{
    ViewData["Title"] = "Newsfeed";
}

<header id="header" style="margin-bottom: 50px">
	<a asp-controller="Home" asp-action="NewsAggregator" class="logo"><strong>Newsfeed</strong></a>
</header>

<div class="box alt">
	<div class="row gtr-50 gtr-uniform">
		@foreach (var item in Model)
		{
			<div class="col-12">
				<div class="header" style="margin-bottom: 20px">
					<header class="minor">
						<h3>@item.Title</h3>
					</header>
					<div class="left date">@item.DatePublished</div>
					<div>
						@item.Description
					</div>
					<a class="url" href="@item.Url">Read more...</a>
					<hr />
				</div>
			</div>
		}
	</div>
	
	<ul class="pagination">
		@if (ViewBag.page == 1)
		{
			<li><span class="button disabled">Prev</span></li>
		}
		else
		{
			<li><a asp-controller="Home" asp-action="NewsAggregator" asp-route-page="@(ViewBag.page - 1)" class="button">Prev</a></li>
		}

		@if (ViewBag.page == ViewBag.lastPage)
		{
			<li><a href="#" class="button disabled">Next</a></li>
		}
		else
		{
			<li><a asp-controller="Home" asp-action="NewsAggregator" asp-route-page="@(ViewBag.page + 1)" class="button">Next</a></li>
		}

	</ul>
	
</div>

Homepage/Views/MapGenerator/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<script src="https://d3js.org/d3.v4.min.js"></script>

<style>
	.links {
		stroke: #000;
		stroke-opacity: 0.2;
	}

	.polygons {
		fill: none;
		stroke: #000;
	}

	.polygons.found {
		fill: #f00;
	}

	.sites {
		fill: #000;
		stroke: #fff;
	}
</style>

<header id="header">
	<a asp-controller="MapGenerator" asp-action="Index" class="logo">Fantasy Map Generator</a>
</header>

<div class="container">
	<div id="map"><svg width="1300" height="1000"></svg></div>
	<div id="controls">

	</div>
</div>

<script>
	var down = false;

	var svg = d3.select("svg").on("touchmove mousemove", moved);
		width = +svg.attr("width"),
		height = +svg.attr("height");

	var sites = d3.range(10000)
		.map(function (d) { return [Math.random() * (width - 80) + 40, Math.random() * (height - 80) + 40]; });

	var voronoi = d3.voronoi()
		.extent([[30, 30], [width - 30, height - 30]]);

	var polygon = svg.append("g")
		.attr("class", "polygons")
		.selectAll("path")
		.data(voronoi.polygons(sites))
		.enter().append("path")
		.call(redrawPolygon);

	var diagram = voronoi(sites);

	findcell([width / 2, height / 2]);

	function moved() {
		if (down) {
			findcelldown(d3.mouse(this));
		} else {
			findcell(d3.mouse(this));
		}
		
	}

	function findcell(m) {
		polygon.attr('fill', '');
		findcelldown(m);
	}

	function findcelldown(m) {
		var found = diagram.find(m[0], m[1], 50);
		if (found)
			polygon._groups[0][found.index].setAttribute('fill', 'green');
	}

	function redraw() {
		polygon = polygon.data(diagram.polygons()).call(redrawPolygon);
	}

	function redrawPolygon(polygon) {
		polygon
			.attr("d", function (d) { return d ? "M" + d.join("L") + "Z" : null; });
	}

	d3.select("svg").on("mousedown", function () {
		down = true;
	}).on( "mouseup", function () {
		down = false;
	});

</script>

Homepage/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<!--
	Editorial by HTML5 UP
	html5up.net | ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
	<title>Sarah Caldow</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="~/css/main.css" />
</head>
<body class="is-preload">

	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
		<div id="main">
			<div class="inner">

				@RenderBody()

			</div>
		</div>

		<!-- Sidebar -->
		<div id="sidebar">
			<div class="inner">

				<!-- Search -->
				<section id="search" class="alt">
					<form method="post" action="#">
						<input type="text" name="query" id="query" placeholder="Search" />
					</form>
				</section>

				<!-- Menu -->
				<nav id="menu">
					<header class="major">
						<h2>Menu</h2>
					</header>
					<ul>
						<li><a asp-controller="Home" asp-action="Index">Home</a></li>
						<li><a asp-controller="Home" asp-action="About">About</a></li>
						<li><a asp-controller="Home" asp-action="NewsAggregator">News Aggregator</a></li>
						<li>
							<span class="opener">RPG Applications</span>
							<ul>
								<li><a asp-controller="MapGenerator" asp-action="Index">Map Generator</a></li>
								<li><a href="#">Harrow Deck</a></li>
							</ul>
						</li>
					</ul>
				</nav>

				<!-- Section -->
				<section>
					<header class="major">
						<h2>Ante interdum</h2>
					</header>
					<div class="mini-posts">
						<article>
							<a href="#" class="image"><img src="images/pic07.jpg" alt="" /></a>
							<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>
						</article>
						<article>
							<a href="#" class="image"><img src="images/pic08.jpg" alt="" /></a>
							<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>
						</article>
						<article>
							<a href="#" class="image"><img src="images/pic09.jpg" alt="" /></a>
							<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>
						</article>
					</div>
					<ul class="actions">
						<li><a href="#" class="button">More</a></li>
					</ul>
				</section>

				<!-- Section -->
				<section>
					<header class="major">
						<h2>Contact Me</h2>
					</header>
					<p>Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
					<ul class="contact">
						<li class="fa-envelope-o"><a href="#">sarah@caldow.org</a></li>
						<li class="fa-phone">(651) 278-3942</li>
					</ul>
				</section>

				<!-- Footer -->
				<footer id="footer">
					<p class="copyright">&copy; Untitled. All rights reserved. Demo Images: <a href="https://unsplash.com">Unsplash</a>. Design: <a href="https://html5up.net">HTML5 UP</a>.</p>
				</footer>

			</div>
		</div>

	</div>

<!-- Scripts -->
	
	<script src="~/js/jquery.min.js"></script>
	<script src="~/js/browser.min.js"></script>
	<script src="~/js/breakpoints.min.js"></script>
	<script src="~/js/util.js"></script>
	<script src="~/js/main.js"></script>

</body>
</html>